spin_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = "Simple Spin application calling OpenAI APIs"
name = "chatgpt"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
openai_key = { required = true, secret = true }

# Chat UI
[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "web"
files = [{ source = "web", destination = "/" }]
[component.trigger]
route = "/..."
watch = ["index.html", "main.js", "styles.css"]

# API
[[component]]
id = "api"
source = "api/target/spin-http-js.wasm"
allowed_http_hosts = ["https://api.openai.com"]
key_value_stores = ["default"]
[component.config]
openai_key = "{{ openai_key }}"
[component.trigger]
route = "/api/..."
[component.build]
command = "npm run build"
workdir = "api"
watch = ["src/index.ts", "package.json"]

# Spin KV explorer component
[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.9.0/spin-kv-explorer.wasm", digest = "sha256:07f5f0b8514c14ae5830af0f21674fd28befee33cd7ca58bc0a68103829f2f9c" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."
